"use client";
import Image from "next/image";
import { useEffect, useMemo, useState } from "react";
import { galleryKinds, type GalleryEntry, type GalleryKind } from "@/content/gallery";

export function GalleryGrid({ entries }: { entries: readonly GalleryEntry[] }) {
  const [filter, setFilter] = useState<"All" | GalleryKind>("All");
  const [activeId, setActiveId] = useState<string | null>(null);
  const visible = useMemo(() => filter === "All" ? entries : entries.filter((entry) => entry.category === filter), [entries, filter]);
  const activeIndex = visible.findIndex((entry) => entry.id === activeId);
  const active = activeIndex >= 0 ? visible[activeIndex] : null;
  useEffect(() => { if (!active) return; const keys = (event: KeyboardEvent) => { if (event.key === "Escape") setActiveId(null); if (event.key === "ArrowRight") setActiveId(visible[(activeIndex + 1) % visible.length].id); if (event.key === "ArrowLeft") setActiveId(visible[(activeIndex - 1 + visible.length) % visible.length].id); }; document.body.style.overflow = "hidden"; addEventListener("keydown", keys); return () => { document.body.style.overflow = ""; removeEventListener("keydown", keys); }; }, [active, activeIndex, visible]);
  return <><section className="gallery-toolbar" aria-label="Filter gallery"><span>Browse stories</span><div>{(["All", ...galleryKinds] as const).map((kind) => <button type="button" className={filter === kind ? "active" : ""} onClick={() => setFilter(kind)} key={kind}>{kind}</button>)}</div></section><section className="gallery-wall" aria-live="polite">{visible.length ? visible.map((entry, index) => <article className={`gallery-story gallery-story--${entry.format}`} key={entry.id} data-reveal><button type="button" className="gallery-story__image" onClick={() => setActiveId(entry.id)} aria-label={`Open ${entry.title}`}><Image src={entry.image} alt={entry.alt} fill unoptimized={entry.image.startsWith("http")} sizes="(max-width:760px) 100vw,50vw" /><span>VIEW STORY</span></button><div className="gallery-story__copy"><p><span>{entry.category}</span><time dateTime={entry.date}>{entry.date}</time></p><h2>{entry.title}</h2><p>{entry.caption}</p><small>{entry.location ? `${entry.location} / ` : ""}FRAME {String(index + 1).padStart(2, "0")}</small>{entry.sourceUrl && <a className="gallery-source" href={entry.sourceUrl} target="_blank" rel="noreferrer">View original post ↗</a>}</div></article>) : <div className="gallery-empty"><span>NO STORIES YET</span><p>This category is ready for its first moment.</p></div>}</section>{active && <div className="gallery-lightbox gallery-lightbox--story" role="dialog" aria-modal="true" aria-label={active.title} onClick={() => setActiveId(null)}><button className="gallery-lightbox__close" type="button" onClick={() => setActiveId(null)}>CLOSE ×</button><button className="gallery-lightbox__nav gallery-lightbox__nav--prev" type="button" onClick={(event) => { event.stopPropagation(); setActiveId(visible[(activeIndex - 1 + visible.length) % visible.length].id); }} aria-label="Previous">←</button><figure onClick={(event) => event.stopPropagation()}><div><Image src={active.image} alt={active.alt} fill unoptimized={active.image.startsWith("http")} sizes="90vw" priority /></div><figcaption><span>{active.category} / {active.date}</span><h2>{active.title}</h2><p>{active.caption}</p>{active.location && <small>{active.location}</small>}{active.sourceUrl && <a className="gallery-source" href={active.sourceUrl} target="_blank" rel="noreferrer">View on LinkedIn ↗</a>}</figcaption></figure><button className="gallery-lightbox__nav gallery-lightbox__nav--next" type="button" onClick={(event) => { event.stopPropagation(); setActiveId(visible[(activeIndex + 1) % visible.length].id); }} aria-label="Next">→</button></div>}</>;
}
