"use client";
import Image from "next/image";
import { FormEvent, useEffect, useState } from "react";
import { galleryKinds, type GalleryEntry } from "@/content/gallery";

export function GalleryManager() {
  const [authenticated, setAuthenticated] = useState(false); const [configured, setConfigured] = useState(true); const [entries, setEntries] = useState<GalleryEntry[]>([]); const [status, setStatus] = useState(""); const [preview, setPreview] = useState("");
  const load = async () => { const [session, posts] = await Promise.all([fetch("/api/gallery/session").then((r) => r.json()), fetch("/api/gallery/posts").then((r) => r.json())]); setAuthenticated(session.authenticated); setConfigured(session.configured && posts.storageReady); setEntries(posts.entries); };
  useEffect(() => { let current = true; Promise.all([fetch("/api/gallery/session").then((response) => response.json()), fetch("/api/gallery/posts").then((response) => response.json())]).then(([session, posts]) => { if (!current) return; setAuthenticated(session.authenticated); setConfigured(session.configured && posts.storageReady); setEntries(posts.entries); }); return () => { current = false; }; }, []);
  const login = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setStatus("Checking…"); const password = String(new FormData(event.currentTarget).get("password") ?? ""); const response = await fetch("/api/gallery/session", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ password }) }); setStatus(response.ok ? "" : "Password not accepted"); if (response.ok) setAuthenticated(true); };
  const publish = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setStatus("Uploading and publishing…"); const form = event.currentTarget; const response = await fetch("/api/gallery/posts", { method: "POST", body: new FormData(form) }); const result = await response.json(); if (!response.ok) return setStatus(result.error ?? "Publish failed"); form.reset(); setPreview(""); setStatus("Published successfully"); await load(); };
  const remove = async (id: string) => { if (!confirm("Delete this gallery post permanently?")) return; const response = await fetch(`/api/gallery/posts/${id}`, { method: "DELETE" }); if (response.ok) { setEntries((current) => current.filter((entry) => entry.id !== id)); setStatus("Post deleted"); } else setStatus("Could not delete post"); };
  if (!configured) return <main className="gallery-admin gallery-admin--notice"><p className="eyebrow">Gallery studio</p><h1>Setup required.</h1><p>Connect a Vercel Blob store and add the three gallery environment variables before publishing from your phone.</p></main>;
  if (!authenticated) return <main className="gallery-admin"><form className="gallery-login" onSubmit={login}><p className="eyebrow">Private gallery studio</p><h1>Welcome back.</h1><label><span>Admin password</span><input type="password" name="password" required autoComplete="current-password" /></label><button type="submit">Enter studio</button>{status && <p role="status">{status}</p>}</form></main>;
  return <main className="gallery-admin"><header><div><p className="eyebrow">Gallery studio / Mobile publisher</p><h1>Create a story.</h1></div><a href="/gallery">View gallery ↗</a></header><form className="gallery-publisher" onSubmit={publish}><label className="gallery-upload"><input type="file" name="image" accept="image/jpeg,image/png,image/webp,image/avif" required onChange={(event) => { const file = event.target.files?.[0]; if (file) setPreview(URL.createObjectURL(file)); }} />{preview ? <Image src={preview} alt="Selected image preview" fill unoptimized /> : <span><b>＋</b> Tap to choose an image<small>JPG, PNG, WEBP or AVIF / 10 MB maximum</small></span>}</label><div className="gallery-publisher__fields"><label><span>Story title *</span><input name="title" required minLength={3} maxLength={120} placeholder="Speaking at…" /></label><label><span>Brief story *</span><textarea name="caption" required minLength={10} maxLength={1000} rows={5} placeholder="What happened and why did the moment matter?" /></label><div><label><span>Type *</span><select name="category">{galleryKinds.map((kind) => <option key={kind}>{kind}</option>)}</select></label><label><span>Date *</span><input name="date" type="date" required /></label></div><label><span>Location</span><input name="location" placeholder="Kampala, Uganda" /></label><label><span>Original post link</span><input name="sourceUrl" type="url" placeholder="https://linkedin.com/posts/…" /></label><label><span>Image description</span><input name="alt" placeholder="Describe the image for accessibility" /></label><label><span>Image shape</span><select name="format"><option value="landscape">Landscape</option><option value="portrait">Portrait</option><option value="square">Square</option></select></label><button type="submit">Publish story ↗</button><p role="status">{status}</p></div></form><section className="gallery-admin-list"><h2>Published stories</h2>{entries.map((entry) => <article key={entry.id}><div><Image src={entry.image} alt="" fill unoptimized={entry.image.startsWith("http")} /></div><span><b>{entry.title}</b><small>{entry.category} / {entry.date}</small></span><button type="button" onClick={() => void remove(entry.id)}>Delete</button></article>)}</section></main>;
}
