"use client";

import { useEffect, useRef } from "react";

const vertex = `attribute vec2 p;void main(){gl_Position=vec4(p,0.,1.);}`;
const fragment = `precision mediump float;uniform float t;uniform vec2 r;uniform vec2 m;
float hash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}
float noise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(hash(i),hash(i+vec2(1,0)),f.x),mix(hash(i+vec2(0,1)),hash(i+vec2(1)),f.x),f.y);}
void main(){vec2 uv=gl_FragCoord.xy/r.xy;uv.x*=r.x/r.y;float n=noise(uv*4.+t*.025)+noise(uv*9.-t*.018)*.45;float edge=smoothstep(.54,.64,n);float d=distance(gl_FragCoord.xy/r,m/r);vec3 base=vec3(.025,.032,.027);vec3 green=vec3(.063,.725,.506);vec3 c=base+green*edge*.12+green*(1.-smoothstep(0.,.32,d))*.025;gl_FragColor=vec4(c,1.);}`;

export function ShaderBackdrop(){const ref=useRef<HTMLCanvasElement>(null);useEffect(()=>{const canvas=ref.current;if(!canvas)return;const reduced=matchMedia("(prefers-reduced-motion: reduce)").matches;const gl=canvas.getContext("webgl",{alpha:false,powerPreference:"low-power"});if(!gl)return;const compile=(type:number,source:string)=>{const shader=gl.createShader(type)!;gl.shaderSource(shader,source);gl.compileShader(shader);return shader};const program=gl.createProgram()!;gl.attachShader(program,compile(gl.VERTEX_SHADER,vertex));gl.attachShader(program,compile(gl.FRAGMENT_SHADER,fragment));gl.linkProgram(program);gl.useProgram(program);const buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,-1,1,1,-1,1,1]),gl.STATIC_DRAW);const point=gl.getAttribLocation(program,"p");gl.enableVertexAttribArray(point);gl.vertexAttribPointer(point,2,gl.FLOAT,false,0,0);const time=gl.getUniformLocation(program,"t"),resolution=gl.getUniformLocation(program,"r"),mouse=gl.getUniformLocation(program,"m");let mx=0,my=0,frame=0,lastDraw=0;const resize=()=>{const d=innerWidth<760?1:Math.min(devicePixelRatio,1.35);canvas.width=Math.round(innerWidth*d);canvas.height=Math.round(innerHeight*d);gl.viewport(0,0,canvas.width,canvas.height)};const move=(e:PointerEvent)=>{const d=innerWidth<760?1:Math.min(devicePixelRatio,1.35);mx=e.clientX*d;my=(innerHeight-e.clientY)*d};const paint=(now:number)=>{gl.uniform1f(time,now*.001);gl.uniform2f(resolution,canvas.width,canvas.height);gl.uniform2f(mouse,mx,my);gl.drawArrays(gl.TRIANGLES,0,6)};const draw=(now:number)=>{if(now-lastDraw>=33){paint(now);lastDraw=now}frame=requestAnimationFrame(draw)};const visibility=()=>{cancelAnimationFrame(frame);if(document.hidden)return;if(reduced)paint(0);else frame=requestAnimationFrame(draw)};resize();if(reduced)paint(0);else frame=requestAnimationFrame(draw);addEventListener("resize",resize,{passive:true});addEventListener("pointermove",move,{passive:true});document.addEventListener("visibilitychange",visibility);return()=>{cancelAnimationFrame(frame);removeEventListener("resize",resize);removeEventListener("pointermove",move);document.removeEventListener("visibilitychange",visibility);gl.deleteProgram(program)}},[]);return <canvas className="shader-backdrop" ref={ref} aria-hidden="true"/>}
